name: blog_explorer
description: A Flutter project to explore blogs.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  hive_generator: ^1.1.1

flutter:
  uses-material-design: true
